main:
  # 소개 메뉴
  - name: About
    url: people
    weight: 200
  - parent: About
    name: me
    url: people
    weight: 210
  - parent: About
    name: goals
    url: /author/김현아/
    weight: 220
  

  # work
  - name: Work
    url: publication
    weight: 300
  - parent: Work
    name: publications
    url: publication
    weight: 310
  - parent: Work
    name: projects
    url: field
    weight: 320

  # univ
  - name: Univ
    url: publication
    weight: 330
  - parent: Univ
    name: activities
    url: /Campus Life/Awards/
    weight: 340
  - #parent: University Life
    #name: Activities
    #url: /Campus Life/Activities/
    #weight: 350

  # interests
  - name: Interests
    url: post
    weight: 600
  #- parent: Updates #publication일듯
  #  name: Notifications
  #  url: notification
  #  weight: 610
  #- parent: Updates
  #  name: News
  #  url: post
  #  weight: 620
  #- parent: Updates
  #  name: Events
  #  url: event
  #  weight: 630

  # 정보 메뉴
  - name: Info
    url: information
    weight: 800
  - parent: Info
    name: Contact 
    url: contact
    weight: 820
